spring:
  application:
    name: skill-tracker-maintain

# Database Configurations
# Local MySQL DB
    #url: jdbc:mysql://localhost:3306/skilltracker?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    #username: root
    #password: pass@word1
# Azure MySQL DB
    #url: jdbc:mysql://mysql-server-skilltracker.mysql.database.azure.com:3306/skilltracker?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    #username: promitbabai
    #password: Mamonbabai-1


  datasource:
    url: jdbc:mysql://mysql-db-skilltracker.mysql.database.azure.com:3306/skilltracker?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: promitbabai
    password: Mamonbabai-1
    jpa:
      hibernate:
        ddl-auto: update
        use-new-id-generator-mappings: false
      generate-ddl: true
      show-sql: true

# KAFKA Configutations
#  kafka:
#    topic:
#      name: skilltrackertopic
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer



server:
  port: 8091


# Eureka Discovery Server Configutations
#eureka:
#  client:
#    instance:
#      hostname: localhost
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#    registerWithEureka: true
#    fetchRegistry: true
#  instance:
#    preferIpAddress: true